version: '3.8'
services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=YourStrongPassword!  # Asegúrate de que esta contraseña sea segura
    ports:
      - "1433:1433"
